POST http://localhost:3000/users/signUp
Content-Type: application/json

{
  "email": "chabgood@gmail.com",
  "password": "moo"
  
}
###

GET http://localhost:3000/users/secret
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIzLCJpYXQiOjE1OTI4NzI1MDgsImV4cCI6MTU5Mjg3NjEwOH0.1HrKseDwcR-dePc8cs41ZsCvGSuZl6mpcbB8Tj9dIfU